### ISSUE TITLE
Row count doesn't match councillor count

### ISSUE THREAD

**Issue by trevortwining** [NiagaraOpenData/region-elected-officials#1]
There are 31 councillors listed on the page https://www.niagararegion.ca/government/council/profiles/default.aspx.

There are only 25 rows in the CSV file.
## Missing Councillors
- Walter Sendzik

**Comment by ConnieM** [comment]
I have attempted to correct. There are now 31.  Zip attached - would not allow a CSV to be uploaded.
[councilelectedofficials.zip](https://github.com/NiagaraOpenData/region-elected-officials/files/366305/councilelectedofficials.zip)

**Comment by trevortwining** [comment]
Fixed!
