### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by nbering** [NiagaraOpenData/region-elected-officials#2]
There doesn't seem to be a license declared for this data set anywhere. I was going to add the license file to this repository if available, but none is declared in the open data portal or at the original meta data url.

http://maps.niagararegion.ca/Metadata/md/Explorer/2443.aspx

**Comment by trevortwining** [comment]
Actually the data is licensed under the Open Government License v2 (Niagara Region). The license terms are available here

https://niagaraopendata.ca/pages/open-government-license-2-0-niagara-region

I tried to add that when I created the project, but I think that it has to be an accepted open license. I'll update the readme to point to that file though.

Thanks for opening this issue though!
